namespace WidgetFTSample
{
    [default_interface]
    runtimeclass Widget1 : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        Widget1();

        Boolean IsAFMFEnabled{ get; set; };
		Boolean IsRISEnabled{ get; set; };
    }
}
