import "Windows.Foundation.idl";
﻿namespace WidgetFT
{

    runtimeclass SampleComponent
    {
        event Windows.Foundation.TypedEventHandler<WidgetFT.SampleComponent, Object> SettingsChanged;
        Boolean  Init();
        void  Refresh();


        ////
        //// Estado global de error
        ////
        Boolean HasError();
        String  Error();

        ////
        //// AFMF (AMD Fluid Motion Frames)
        ////
        Boolean AFMF_Supported();
        Boolean AFMF_Enabled();
        Boolean AFMF_SetEnabled(Boolean enable);

        ////
        //// RIS (Radeon Image Sharpening)
        ////
        Boolean RIS_Supported();
        Boolean RIS_Enabled();
        Boolean RIS_SetEnabled(Boolean enable);

        Int32   RIS_Sharpness();
        Int32   RIS_SharpnessMin();
        Int32   RIS_SharpnessMax();
        Boolean RIS_SetSharpness(Int32 value);

        ////
		//// RSR (Radeon Super Resolution)
        /// 
		Boolean RSR_Supported();
		Boolean RSR_Enabled();
		Boolean RSR_SetEnabled(Boolean enable);

        // ---------------------------------------------------------------------
        //  BOOST (AMD Boost)                                                   
        // ---------------------------------------------------------------------
        Boolean Boost_Supported();                                             
        Boolean Boost_Enabled();                                               
        Boolean Boost_SetEnabled(Boolean enable);                              

        Int32   Boost_Resolution();                                            
        Int32   Boost_ResolutionMin();                                         
        Int32   Boost_ResolutionMax();                                         
        Boolean Boost_SetResolution(Int32 value);                              

        Boolean Boost_SetPerfMin();     // Convenience → minValue              
        Boolean Boost_SetPerfMax();     // Convenience → maxValue              
    }
}
